// Code generated by "stringer -type ClientType endpoint.go"; DO NOT EDIT.

package conf

import "strconv"

const _ClientType_name = "UnknownEventTCPHTTPPost"

var _ClientType_index = [...]uint8{0, 12, 15, 23}

func (i ClientType) String() string {
	if i < 0 || i >= ClientType(len(_ClientType_index)-1) {
		return "ClientType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ClientType_name[_ClientType_index[i]:_ClientType_index[i+1]]
}
