// Code generated by "stringer -type FlagID flag.go"; DO NOT EDIT.

package cmd

import "strconv"

const _FlagID_name = "UnknownFlagaddresscltTypeconHiscxnLimcxnNumdirendpointfilelogHisportrateMinrateSecrepeatsaveReqsaveReqDirsaveRessaveResDirsleepMstmoCxntmoRdStmoSectmoWrSwildcardlogLvlconLvlconFlat"

var _FlagID_index = [...]uint8{0, 11,18,25,31,37,43,46,54,58,64,68,75,82,88,95,105,112,122,129,135,141,147,153,161,167,173,180}

func (i FlagID) String() string {
	if i < 0 || i >= FlagID(len(_FlagID_index)-1) {
		return "FlagID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FlagID_name[_FlagID_index[i]:_FlagID_index[i+1]]
}
