// Code generated by "stringer -type FlagID flag.go"; DO NOT EDIT.

package cmd

const _FlagID_shorthand = " acylndifgpmsrqkojeuvtxw" // spare b,z
//const _FlagID_shorthand = " acylndifgpmsrqkojeuvtxw  z"

//var _FlagID_shorthand_idx = [...]uint8{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28}
var _FlagID_shorthand_idx = [...]uint8{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24}

func (i FlagID) Flag() string {
	if i < 0 || i >= FlagID(len(_FlagID_shorthand_idx)-1) {
		//return "FlagID(" + strconv.FormatInt(int64(i), 10) + ")"
		return ""
	}
	return _FlagID_shorthand[_FlagID_shorthand_idx[i]:_FlagID_shorthand_idx[i+1]]
}
